# Generated by Django 3.1.7 on 2021-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('company_location', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=500)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(max_length=300)),
                ('company_website', models.URLField(blank=True, max_length=500, null=True)),
                ('company_location', models.CharField(max_length=200)),
                ('job_type', models.CharField(choices=[('remote', 'remote'), ('remote-only', 'remote-only'), ('not-remote', 'not-remote')], max_length=20)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('level', models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Mid level', 'Mid level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('how_to_apply', models.CharField(max_length=200)),
                ('target', models.CharField(max_length=500)),
                ('currency', models.CharField(blank=True, max_length=200, null=True)),
                ('min_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('max_salary', models.PositiveIntegerField(blank=True, null=True)),
                ('tag', models.ManyToManyField(blank=True, to='jobs.Tag')),
            ],
        ),
    ]
