# Generated by Django 3.1.7 on 2021-03-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210308_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seniority',
            field=models.CharField(choices=[('Beginner', 'Beginner'), ('Junior', 'Junior'), ('Mid level', 'Mid level'), ('Senior', 'Senior'), ('Lead', 'Lead'), ('Manager', 'Manager')], default=1, max_length=30),
            preserve_default=False,
        ),
    ]
